### ISSUE TITLE
Enable options for durable & expiryPolicy in order to create durable subscriptions

### ISSUE THREAD

**Issue by haneev** [vcabbage/amqp#133]
Currently there is no way to create a durable shared subscription, because you have no access to the durable property on the `source` object in the receiver. Creating new functions like `LinkDurable(enabled bool)` and `ExpiryPolicy(policy symbol)` (or an enum for expiry policy) would enable this functionality.

**Comment by vcabbage** [comment]
Thanks for reporting this!

I opened PR #137 to add source durability and expiry policy options. I adjusted the API a little from your example due to durability having three options and since these options can be applied to the source and/or the target. I've only implemented them for the source so far. I'm planning on deferring the target versions for now, unless you know of a use case for them.

I'm going to wait a couple days before merging. Any input you have on the API would be welcome and appreciated.
