### ISSUE TITLE
Error - Link with name already exists

### ISSUE THREAD

**Issue by OdeToCode** [vcabbage/amqp#143]
I'm seeing this error message that originates from [client.go line 523](https://github.com/vcabbage/amqp/blob/737d254fced3c8c602d642fd6bce8488a0fa9819/client.go#L523) 

What's odd is that I never see the problem in development, but only in production, where the error appears with great frequency. The app is sending messages to an Azure Event Hub using code seen [here](https://github.com/OdeToCode/azgov/blob/master/pkg/azure/events.go). 

I'm not sure how to go about debugging or reproducing the error outside of production. It feels like a race at first, but the app runs from the console, doesn't spawn additional go routines, and shouldn't be using the outer event hub object concurrently. Since the error only appears in a specific environment, I suspect it might be something different happening in the build environment or installed binaries.

**Comment by vcabbage** [comment]
That check exists primarily to avoid someone erroneously using the same `LinkName` option twice on the same link. I did a quick search of your repo and the Azure repos and don't see any usage of that option. When that option isn't set it randomly generates a link name using:
https://github.com/vcabbage/amqp/blob/ffd2c0497a112275c2a265448c94be3e80d35b05/client.go#L281-L286

Can you confirm that the logged link name is a random base64 string?

Since each invocation creates a new rand source it's conceivable that the same name would be generated if the links were created in quick enough succession as to get the same time value. This may be more likely to occur on Windows as I think it has lower time resolution in Go than other platforms, though I don't recall the details.

Either way, I believe that the current usage of seeding on each invocation is a bug and we should change it to either use a package level rand source or `crypto/rand`.

Does this sound like a plausible explanation for your issue?

(PS: I watched a bunch of your Pluralsight videos when I was first learning software dev, thanks for those!)

**Comment by OdeToCode** [comment]
Yes - it is a base 64 string, and the explanation sounds extremely plausible. I copied `randString` into a loop inside a test harness and can see triplicates in the output. Thanks for looking at this. 

(P.S.  - Wow, that's awesome! Thanks for letting me know!)

**Comment by devigned** [comment]
The stress testing we ran on Event Hub was not creating a massive number of links in succession, but rather opening long running links. I could see why this would not have popped up in EH validation.

**Comment by vcabbage** [comment]
Thanks for reporting this! Fix has been merged and tagged as v0.10.2. Feel free to re-open this issue if that doesn't end up resolving the problem.

**Comment by OdeToCode** [comment]
Thanks for the quick fix - it looks good on my end.
