### ISSUE TITLE
Interfaces for mocking purposes

### ISSUE THREAD

**Issue by Chronojam** [vcabbage/amqp#159]
Heya.

Honestly im not even sure if this is something you'd really want; but ive run into a couple of problems when trying to mock out some implementations here for testing (feel free to tell me im doing it wrong etc.)

but I think it might be a good idea to express certain components as interfaces, rather than concrete types, eg.

Session, Receiver and Sender for example, ive got a fork of roughly what im proposing here https://github.com/lakahq/amqp

This'll allow us to create mocks from our applications/programs/clients etc.

```
type mockAmqpSession struct {}

// Etc.
func (m *mockAmqpSession) NewSender() (amqp.Sender, error) {
  return &mockSender{}, nil
}

```

Appreciate that its normal practice to have these interfaces in the calling library, however i dont think its possible to create the deep mocking structure required in this case. eg

```
type AMQPMockSession interface {
  Close()

  // amqp.Session will not satisfy this signature
  NewSender() (AMQPMockSender, error)
}

type AMQPMockSender interface {
  // More Stuff
}

type MyCoolTopicGrabber struct {
    Session AMQPMockSession
}
func NewCoolTopicGrabber(sess AMQPMockSession) {

return &MyCoolTopicGrabber {
  Session: sess
}
}

func main() {
        // Stuff
	session, err := client.NewSession()
	if err != nil {
		log.Fatal("Creating AMQP session:", err)
	}

        // YouGetNothingGoodDaySir.jpg
        NewCoolTopicGrabber(session)
}
```

If this is something you'd consider - I could commit to some time to adding this.

**Comment by vcabbage** [comment]
Hi @Chronojam,

The approach I take and recommend to others is to create an abstraction around a library that fits with the consuming application. That way you can mock your abstraction or swap out the implementation if it becomes necessary. It also tends to reduce tight coupling of code.

As an example, some of the applications I work on use a PostgreSQL database. Instead of having anything depend on `database/sql` directly I'll create an abstraction package that contains all the SQL specific logic and exposes things like `db.AddEvent(...)` or `db.RemoveEvent(...)`.

I'm unlikely to switch to returning interfaces for a few reasons:
* It more or less prevents exposing fields on the returned struct. This isn't strictly true of course, but needing to type assert back to a concrete type makes for less than stellar usability and would be a non-starter for your use case.
* It turns API additions into breaking changes. If you were to create a mock for an interface declared in this library and I added a new method to the interface it would cause your code to fail to compile until you added the method to your mock. This doesn't happen with concrete types (technically there are some ways a method addition can cause problems when embedding is involved, but they're much less likely to occur).
* A bit subjective, but I think the documentation generated by godoc is worse for interfaces. With an interface the index would show only `type Sender` instead of `type Sender` followed by all the exported methods and their signatures.

I hope this helps illuminate some of the trade-offs and provides a potential work around for you. This isn't a "hard no," so if there's something I'm missing or if you have any questions please let me know.

**Comment by Chronojam** [comment]
Heya @vcabbage 

Thanks for taking the time to write out such a detailed response, everything you've said makes total sense to me, and the reasons you've listed i think are totally justified; ive had some fresh perspective so pretty sure this is no longer required (at least for our use case) so im going to close this.

Thanks again :)
