### ISSUE TITLE
Add ability to configure receiver's target and sender's source

### ISSUE THREAD

**Issue by amenzhinsky** [vcabbage/amqp#19]
It's needed at least to implement request-response operations (reply-to):
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-request-response

Right now it's not possible:
https://github.com/vcabbage/amqp/blob/746c1d6d9c9af8074e67fb9173f57cf59aa48a5f/client.go#L692-L705

Probably we should add funcs like `LinkSource(s *Source)` and `LinkTarget(t *Target)`
Any thoughts?

**Comment by vcabbage** [comment]
For now, I think adding `LinkSourceAddress(s string)` and `LinkTargetAddress(s string)` should work.

This will add some duplication with `LinkAddress(s string)`, which I'm not a fan of. Instead of removing it right away I think it should be marked deprecated.

I'd like to avoid exposing the `source` and `target` structures, unless it's really necessary.
