### ISSUE TITLE
support for other message formats other than the default uint32(0)

### ISSUE THREAD

**Issue by devigned** [vcabbage/amqp#35]
https://github.com/vcabbage/amqp/blob/ccafaa7153e8efde1caf028aae0990dea70de06c/client.go#L274

One such example for non-default message formats is sending batch messages in Azure Service Bus. The following message format is used in the Java lib.

```java
public static final int AMQP_BATCH_MESSAGE_FORMAT = 0x80013700; // 2147563264L;
```
[via here](https://github.com/Azure/azure-event-hubs-java/blob/c1365b956f2b0bf9f65db92385a6d433f5dba28c/azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/impl/AmqpConstants.java#L60)

Perhaps, send should support `TransferOption` variadic arguments. Thoughts?

**Comment by vcabbage** [comment]
Would it make sense to add a `Format` field to the `Message` struct?

What is the format used for? The spec doesn't go into much detail about it.

**Comment by devigned** [comment]
I think it would make sense on the message.

I don’t know what else message format is used for. As you said, there not much to grok from the spec. I’ll ask amongst messaging folks and ping back if I get a better answer.

**Comment by vcabbage** [comment]
Looking at the usage in the Java lib, it seems the `AMQP_BATCH_MESSAGE_FORMAT` code might be a workaround for proton-j not supporting multiple data sections. This lib doesn't currently support that either, but only because I didn't need that when I first implemented it and I haven't decided on a good way to expose that on the message type. Would multiple data section support be useful to you?

https://github.com/Azure/azure-event-hubs-java/blob/c1365b956f2b0bf9f65db92385a6d433f5dba28c/azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/impl/MessageSender.java#L273-L305

**Comment by devigned** [comment]
That is precisely what I'm implementing right now, so yes, it would be useful. If you feel like multiple data section support is something you'd like to expose from this library, I'll gladly use it.
