### ISSUE TITLE
Fix flaky integration tests

### ISSUE THREAD

**Issue by vcabbage** [vcabbage/amqp#8]
Integration tests frequently fail due to context or leakcheck timeouts. Should bump up the timeouts or add a scaling option to use in CI.

Example: https://travis-ci.org/vcabbage/amqp/jobs/328595062

**Comment by vcabbage** [comment]
As far as I can tell, this is Service Bus throttling the standard instance used for integration test. I'm not willing to pay for premium out of my own pocket so I guess I'll just deal with the failures for now.

**Comment by devigned** [comment]
@vcabbage I might be able to help out with this. Interested?

**Comment by vcabbage** [comment]
@devigned That would be great, thanks!

**Comment by devigned** [comment]
I’m looking into it.

**Comment by devigned** [comment]
@vcabbage still working on this with @joshgav. 

Another thought on the throttling... I may have missed the code, but I don't see anything decrementing or increasing the link credit on the sender. Perhaps, this is a source of some of the throttling issues.

**Comment by devigned** [comment]
Nvm. It looks like link credit is being handled per the spec.

**Comment by devigned** [comment]
I have an update about server busy errors.

AMQP flow control is at link level and EH server busy is measured by metrics at namespace level. There is no good solution to distribute the limit across links that can be created for different scenarios. At the very beginning our flow control delayed processing messages if namespace limit was hit but people complained about latency without realizing their usage was the cause. Letting the clients know that they are exceeding the limit with server busy errors may be good in most cases so that applications can decide what to do with it.

The Azure broker implementation will return `com.microsoft:server-busy` to indicate the namespace is out of quota and to back off. The .NET client backs off and retries in 10 seconds.

Based on this, it doesn't seem like a good idea to handle vendor specific retries in the library. What might make sense is to handle them in the integration tests to make them more robust to this error. Either that, or provide some sort of retry policy for the sender.

**Comment by vcabbage** [comment]
I haven't seen any of these failures in a while. I suspect the root cause was the incorrect flow control implementation, which was fixed in #103.
