### ISSUE TITLE
received message larger than max size of -1

### ISSUE THREAD

**Issue by devigned** [vcabbage/amqp#91]
Without setting the `amqp.LinkMaxMessageSize(...)` on a receiver, the max message size is -1, which causes an error. After setting `amqp.LinkMaxMessageSize(...)` I'm again able to receive messages.

**Comment by vcabbage** [comment]
Since `max-message-size` is a `uint64`, I suspect the maximum `uint64` value is being set somewhere and overflowing on the conversion below.

I can put in a fix tonight or you can send a PR if you'd like.

https://github.com/vcabbage/amqp/blob/707d8813ac8c38786ea13e078c86f1b6b58509a3/client.go#L1439

**Comment by devigned** [comment]
@vcabbage you were right event hubs was sending over `18446744073709551615` as the max size and overflowing the int.
